export const groupOptions = [
    { id: 'education', value: 'education', label: 'Education', icon: '🎓' },
    { id: 'finance', value: 'finance', label: 'Finance', icon: '💰' },
    { id: 'healthcare', value: 'healthcare', label: 'Healthcare', icon: '🏥' },
    { id: 'ecommerce', value: 'ecommerce', label: 'E-commerce', icon: '🛒' },
    { id: 'social_media', value: 'social_media', label: 'Social Media', icon: '📱' },
    { id: 'gaming', value: 'gaming', label: 'Gaming', icon: '🎮' },
    { id: 'productivity', value: 'productivity', label: 'Productivity', icon: '⏱️' },
    { id: 'travel', value: 'travel', label: 'Travel', icon: '✈️' },
    { id: 'food_delivery', value: 'food_delivery', label: 'Food Delivery', icon: '🍔' },
    { id: 'real_estate', value: 'real_estate', label: 'Real Estate', icon: '🏠' },
    { id: 'fitness', value: 'fitness', label: 'Fitness', icon: '💪' },
    { id: 'entertainment', value: 'entertainment', label: 'Entertainment', icon: '🎭' },
    { id: 'news_media', value: 'news_media', label: 'News & Media', icon: '📰' },
    { id: 'transportation', value: 'transportation', label: 'Transportation', icon: '🚗' },
    { id: 'environment', value: 'environment', label: 'Environment', icon: '🌿' },
    { id: 'iot', value: 'iot', label: 'IoT', icon: '🔌' },
    { id: 'cybersecurity', value: 'cybersecurity', label: 'Cybersecurity', icon: '🔒' },
    { id: 'ar_vr', value: 'ar_vr', label: 'AR/VR', icon: '🥽' },
    { id: 'music', value: 'music', label: 'Music', icon: '🎵' },
    { id: 'nonprofit', value: 'nonprofit', label: 'Non-profit', icon: '🤝' },
    { id: 'marketing', value: 'marketing', label: 'Marketing', icon: '📣' },
    { id: 'ai', value: 'ai', label: 'AI', icon: '🤖' },
    { id: 'dev_tools', value: 'dev_tools', label: 'Dev Tools', icon: '🛠️' }
  ]
  
  export const contributionOptions = [
    { id: 'docs', value: 'docs', label: 'Documentation', icon: '📚' },
    { id: 'features', value: 'features', label: 'Features', icon: '✨' },
    { id: 'ui_design', value: 'ui_design', label: 'UI Design', icon: '🎨' },
    { id: 'optimization', value: 'optimization', label: 'Optimization', icon: '⚡' },
    { id: 'testing', value: 'testing', label: 'Testing', icon: '🧪' },
    { id: 'localization', value: 'localization', label: 'Localization', icon: '🌐' },
    { id: 'reviews', value: 'reviews', label: 'Code Reviews', icon: '👀' },
    { id: 'bugs', value: 'bugs', label: 'Bug Finding', icon: '🐛' },
    { id: 'automating', value: 'automating', label: 'Automating', icon: '🤖' },
    { id: 'community', value: 'community', label: 'Community Management', icon: '👥' }
  ]

export const languagesOptions = [
    { id: 'javascript', value: 'javascript', label: 'JavaScript', icon: '🟨' },
    { id: 'python', value: 'python', label: 'Python', icon: '🐍' },
    { id: 'java', value: 'java', label: 'Java', icon: '☕' },
    { id: 'typescript', value: 'typescript', label: 'TypeScript', icon: '🔷' },
    { id: 'csharp', value: 'csharp', label: 'C#', icon: '♯' },
    { id: 'php', value: 'php', label: 'PHP', icon: '🐘' },
    { id: 'c_plus_plus', value: 'c_plus_plus', label: 'C++', icon: '➕' },
    { id: 'ruby', value: 'ruby', label: 'Ruby', icon: '💎' },
    { id: 'c', value: 'c', label: 'C', icon: '🔵' },
    { id: 'go', value: 'go', label: 'Go', icon: '🐹' },
    { id: 'swift', value: 'swift', label: 'Swift', icon: '🦅' },
    { id: 'kotlin', value: 'kotlin', label: 'Kotlin', icon: '🤖' },
    { id: 'rust', value: 'rust', label: 'Rust', icon: '🦀' },
    { id: 'dart', value: 'dart', label: 'Dart', icon: '🎯' },
    { id: 'scala', value: 'scala', label: 'Scala', icon: '🔺' },
    { id: 'shell', value: 'shell', label: 'Shell', icon: '🐚' },
    { id: 'objective_c', value: 'objective_c', label: 'Objective-C', icon: '🍏' },
    { id: 'r', value: 'r', label: 'R', icon: '📊' },
    { id: 'perl', value: 'perl', label: 'Perl', icon: '🐪' },
    { id: 'haskell', value: 'haskell', label: 'Haskell', icon: 'λ' },
    { id: 'elixir', value: 'elixir', label: 'Elixir', icon: '💧' },
    { id: 'clojure', value: 'clojure', label: 'Clojure', icon: '🌿' },
    { id: 'lua', value: 'lua', label: 'Lua', icon: '🌙' },
    { id: 'matlab', value: 'matlab', label: 'MATLAB', icon: '📐' },
    { id: 'groovy', value: 'groovy', label: 'Groovy', icon: '🎵' }
];